### ISSUE TITLE
Run command panics with simple pattern

### ISSUE THREAD

**Issue by strokirk** [ast-grep/ast-grep#275]
Hi! This is a very cool tool. When trying it out, I encountered an error first thing I did.

Running the following pattern

```
sg run -p '$A'
```

in https://github.com/django/django crashes with the following stack trace:

```
./django/__main__.py
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/danstrokirk/.cargo/registry/src/github.com-1ecc6299db9ec823/ast-grep-0.2.6/src/print/colored_print.rs:282:16
stack backtrace:
   0:        0x10077e954 - std::backtrace_rs::backtrace::libunwind::trace::h9b702eac7a4070d0
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10077e954 - std::backtrace_rs::backtrace::trace_unsynchronized::haaee73adfb0c25c3
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10077e954 - std::sys_common::backtrace::_print_fmt::h9513f81124e0aa0a
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x10077e954 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3145938d04ff7c57
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x100799de4 - core::fmt::write::hbacf27bbc49db694
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/fmt/mod.rs:1208:17
   5:        0x10077b054 - std::io::Write::write_fmt::h32e7f478b854f67c
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/io/mod.rs:1682:15
   6:        0x10077e768 - std::sys_common::backtrace::_print::he5d8a9c79d25b68e
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x10077e768 - std::sys_common::backtrace::print::h4486a18800044a6f
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x10077fedc - std::panicking::default_hook::{{closure}}::hc7cd3b246ab7c4c4
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:267:22
   9:        0x10077fc34 - std::panicking::default_hook::hd88ef44e7b3e6ae9
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:286:9
  10:        0x100780500 - std::panicking::rust_panic_with_hook::h773ea47880413b2b
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:688:13
  11:        0x1007802e0 - std::panicking::begin_panic_handler::{{closure}}::h95be8f1d07e6ccdd
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:577:13
  12:        0x10077edbc - std::sys_common::backtrace::__rust_end_short_backtrace::h46a414ab13b823d9
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x10078007c - rust_begin_unwind
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
  14:        0x1007bc0c0 - core::panicking::panic_fmt::h0e282a60229c0f3d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
  15:        0x1007bc154 - core::panicking::panic::he455c9b70f468dbc
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
  16:        0x100492260 - <sg::print::colored_print::ColoredPrinter<W> as sg::print::Printer>::print_matches::h8f1ca8be1396fa65
  17:        0x1003c9ad8 - sg::run::match_one_file::h194d6ffea75d4569
  18:        0x1003c84b0 - <sg::run::RunWithInferredLang<P> as sg::utils::Worker>::consume_items::hea0bbebcda62c24c
  19:        0x100468d94 - sg::utils::run_worker::h2cf3298b40762df0
  20:        0x1003c6e00 - sg::run::run_with_pattern::h4ff5cff4404fa772
  21:        0x1004cd5cc - sg::main::hb1c49c2a55fbf2ef
  22:        0x10034fc98 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5b14b8e0292b2659
  23:        0x1003b0034 - std::rt::lang_start::{{closure}}::h781f6b3635dc1024
  24:        0x1007755ec - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6b3d20c433ee9935
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:606:13
  25:        0x1007755ec - std::panicking::try::do_call::hea337837a58ecc7f
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  26:        0x1007755ec - std::panicking::try::hbb3a49978396e60d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  27:        0x1007755ec - std::panic::catch_unwind::he3380a58cafe1d50
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  28:        0x1007755ec - std::rt::lang_start_internal::{{closure}}::hdb52e0a41b641527
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:48
  29:        0x1007755ec - std::panicking::try::do_call::h48c7d70387114ef1
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  30:        0x1007755ec - std::panicking::try::h0d5a8f241b0e4511
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  31:        0x1007755ec - std::panic::catch_unwind::h582952084c18efd0
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  32:        0x1007755ec - std::rt::lang_start_internal::h0cdebe2c4a3b171e
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:20
  33:        0x1004ce0b4 - _main
```

**Comment by HerringtonDarkholme** [comment]
`$A` is a wildcard pattern so it can matches everything. You can try another pattern.

Changing the error message is a good point though.
